### ISSUE TITLE
Request unsilencing of journa.host

### ISSUE THREAD

**Issue by richfelker** [hachyderm/community#211] opened 2022-12-17 14:39 UTC
### What domain(s) need to be added or removed from our blocklist?

As noted in https://github.com/hachyderm/community/issues/198, silencing (now called limited, I think) is more disruptive than it probably should be. The silencing of `journa.host` is particularly causing me real problems trying to interact with discussions around Mastodon best practices for journalists and news institutions:

- I'm missing all notifications of replies from users on that instance
- Threads appear broken and impossible to follow
- I'm probably making nuisance replies duplicating things people have already said that I can't see.
- Etc.

The only workaround I know is to follow *everyone* potentially relevant from that instance and mute them, one at a time as I discover their handles in broken threads. This does not seem practical.

As far as I can tell from #65, there does not appear to be any justification for leaving it silenced. If there is, can we discuss this and try to reach a solution that's acceptable for everyone? If the concern is that their moderation policies are not sufficiently strong, but 4-5 nines of users there are not posting anything we would deem "should have been moderated", maybe it would work to just silence any individual accounts there which are posting problematic things (?).

**Comment by quintessence** [comment] 2022-12-17 20:10
👋 I thought I wrote in here - apologies! 

It looks like silencing is more disruptive than we originally understood. The expected behavior was that users could follow / interact with accounts normally, the content just wouldn't appear in the Federated Timeline unrequested. 

As you acknowledged, the one-by-one solution wouldn't work here due to scale.

We're currently looking at an image caching issue, but I will circle back around to look at this once that is complete.

**Comment by quintessence** [comment] 2022-12-23 21:39
👋 Update: for now, we've unmoderated journa.host. This means that we are now federating normally with journa.host; however, we are still more broadly looking at what we can do to successfully find a "medium" hammer that is less drastic than Suspend but still allows us to take some action where warranted.

Thank you all for your patience :)

**Comment by quintessence** [comment] 2022-12-27 21:38
Update x2:

* Going to close this issue
* For some reason, that we are troubleshooting, the "unsilence" isn't propagating so it might take a moment for things to look normal again while we try things to fix that.

**Closed by quintessence** 2022-12-27 21:38 UTC
Labels: Domain Block Request or Report
