### ISSUE TITLE
Hachydermians cannot see the polls from a specific account @mastodon.social but  can see normal Toots

### ISSUE THREAD

**Issue by basicallyabidoof** [hachyderm/community#270] opened 2023-01-23 19:22 UTC
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
2. When are you seeing the issue? When you are submitting posts? Uploading media?
3. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

Please note that if there are issues with individual apps or with Mastodon core that
we can work with you to determine that to be the case, but we can not fix third party apps
and do not directly contribute to the Mastodon project at this time.

### How long have you noticed this issue?

Since yesterday morning

### What geographic region are you accessing Hachyderm from?

Midwest USA

### Is there anything else that we should know?

The account is dungeons@mastodon.social

**Comment by freiheit** [comment] 2023-01-23 19:42
I think I'm unable to reproduce.

Looking at: https://hachyderm.io/@dungeons@mastodon.social/109740165084181560

I see both the older poll results and the latest open poll:
![image](https://user-images.githubusercontent.com/19813/214134008-5c2874d7-0506-4c13-a336-e2a8e6c63667.png)

Are you using an app, or is this via the web UI?

**Comment by basicallyabidoof** [comment] 2023-01-23 19:59
That's really strange, both myself @witchofwinter@hachyderm.io and @ESG@hachyderm.io can't see them. I can't see them on either the app or web ui, unless I sign out and directly visit them.

**Comment by EricStG** [comment] 2023-01-23 20:43
@ESG@hachyderm.io here
Clicking @freiheit's link, I can see the toots
But they don't show up on my home. They don't show up when I on the account (https://hachyderm.io/@dungeons@mastodon.social) either!
![image](https://user-images.githubusercontent.com/6012934/214145678-a44e8f62-fcc9-4c3d-903d-f1f21492cfe4.png)
That's both using the hackyderm.io on desktop and Tusky on mobile

**Comment by freiheit** [comment] 2023-01-23 23:08
What about at https://hachyderm.io/@dungeons@mastodon.social/with_replies ?
(seems like all the polls are replies)

**Comment by EricStG** [comment] 2023-01-23 23:14
Those I see
Still weird that they stopped showing under Posts (although I still see old polls) and in my home feed though.
And yeah, the pools are all replies to each other, in a single giant thread.

**Comment by EricStG** [comment] 2023-01-26 15:45
FYI, I started seeing that thread again today after the bot started a new thread

**Comment by basicallyabidoof** [comment] 2023-01-26 15:49
As am I, not sure what happened there.

**Comment by freiheit** [comment] 2023-01-30 18:10
Since problem seems to have fixed itself, I'll close this ticket.

**Closed by freiheit** 2023-01-30 18:10 UTC
Labels: Reporting Service Issue
