### ISSUE TITLE
Emoji Name Length and Character Limits

### ISSUE THREAD

**Issue by jmerritt** [hachyderm/community#72] opened 2022-11-20 19:11 UTC
Extremely low priority fluff issue, but in the interest of using emoji in our usernames would it be prudent to shorten their naming?

_ex1-_ `:nix:` vs `:nix_snowflake_logo:`

Usernames have a char limit that is pretty easy to hit with an emoji or two.
Thank you for the consideration.

**Comment by slamp** [comment] 2022-11-20 19:37
This is a duplicate of https://github.com/hachyderm/community/issues/54

**Comment by jmerritt** [comment] 2022-11-20 22:43
> This is a duplicate of https://github.com/hachyderm/community/issues/54

Thanks for that don't know how I missed it. Closing.

**Closed** 2022-11-27 06:32 UTC
