### ISSUE TITLE
Images 404

### ISSUE THREAD

**Issue by amencarini** [hachyderm/community#213] opened 2022-12-17 18:42 UTC
### Please describe the issue you are seeing.

Hi,
I'm seeing images from Hachyderm not being available.

I have this toot available on my timeline: https://hachyderm.io/@thomasfuchs/109530103768827792

When tapping on the image on the Toot app, it redirects to this URL:

https://hachyderm.io/system/media_attachments/files/109/530/102/400/672/238/original/3f32d78d7879ef95.png

Which 404s.

I've had this behaviour with several toots of users hosted on Hachyderm.

### How long have you noticed this issue?

n/a

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by amencarini** [comment] 2022-12-17 19:38
On the other hand, same author, works ok:
https://hachyderm.io/@thomasfuchs/109530664424541667

**Comment by quintessence** [comment] 2022-12-17 19:46
👋 Mod here

Thank you for the report! We see it - looks like it's a global issue. We're still determining the cause but are actively working on it as I type this. Nóva is also streaming the fix process live on her Twitch channel for anyone interested in watching (I realize the time may be late for you in Europe in general). -> https://twitch.tv/krisnova

**Comment by quintessence** [comment] 2022-12-18 03:55
This issue should be resolved with the cache fixes. Please open a new issue if it persists :D

**Closed by quintessence** 2022-12-18 03:55 UTC
Labels: Reporting Service Issue
