### ISSUE TITLE
status.hachyderm.io not reporting system outages

### ISSUE THREAD

**Issue by superchromix** [hachyderm/community#120] opened 2022-11-29 17:32 UTC
At the moment, the Grafana dashboard is down, and new posts from other servers are not reaching hachyderm.io.  This is not reflected on the status page (status.hachyderm.io), which simply says "All systems operational".

**Comment by quintessence** [comment] 2022-11-29 19:11
Hello!

Right now the systems are operational again but we're going to take a look at the Status Page to see where the issue is otherwise. Thank you for letting us know! 

Closing issue as I've moved it to our internal tracker.

**Closed by quintessence** 2022-11-29 19:11 UTC
