### ISSUE TITLE
Search is dragging

### ISSUE THREAD

**Issue by timbray** [hachyderm/community#387] opened 2023-04-05 21:12 UTC
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
2. When are you seeing the issue? When you are submitting posts? Uploading media?
3. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

Please note that if there are issues with individual apps or with Mastodon core that
we can work with you to determine that to be the case, but we can not fix third party apps
and do not directly contribute to the Mastodon project at this time.

### How long have you noticed this issue?

Last few minutes

### What geographic region are you accessing Hachyderm from?

Vancouver Canada

### Is there anything else that we should know?

I searched for @jwz because I didn't know what instance he's on and wanted to reference him, it went away for several minutes and then there was a flurry of "504 gateway timeout" floaties.  Went to another instance where I have an account and the search came back instantly.

**Comment by timbray** [comment] 2023-04-05 21:13
(Sorry, not just jwz, seems to be all searches at the moment)

**Comment by llimllib** [comment] 2023-04-05 21:26
Duplicate of #385

**Comment by Preskton** [comment] 2023-04-30 17:45
Howdy, folks - as commented in the other issue, we disabled full-text search for the moment while we rebuild the full-text search cluster. Please note rebuilding the cluster is currently on the backlog but not yet scheduled.

**Closed by Preskton** 2023-04-30 17:45 UTC
Labels: Reporting Service Issue, Infra Team
