### ISSUE TITLE
Still unable to follow anyone on hachyderm.io after instance unblocking

### ISSUE THREAD

**Issue by ambihelical** [hachyderm/community#250] opened 2023-01-02 23:39 UTC
### What would you like to discuss with us or let us know?

I'm on qoto.org, which was recently unblocked, thanks for changing that!  However I'm still unable to follow anyone on hachyderm.  Following someone from a search result (on qoto.org) will initially look like it works, but a refresh of the page shows "Cancel Follow Request" instead of "Unfollow". 

 I suspect that this bug is the root cause, https://github.com/mastodon/mastodon/issues/22133, since qoto.org was originally blocked, and then silenced, and now not blocked at all (at least according to the About page), however this is just a guess.  

Thanks in advance for anything that can be done.

**Comment by dmah42** [comment] 2023-01-04 14:35
the issue referenced is marked fixed as of ~3w ago but this is after the release of 4.0.2.  even if the bug is fixed, i suspect some sort of backfill (or a silence/unsilence event) would need to be triggered to get users into the right state.

taking a look at the fix for the bug, i agree that this may be the root cause.  we are at the mercy of upstream cutting a new release with the fix, or creating a local fork/snapshot upon which we can apply the same patch.

**Comment by lypanov** [comment] 2023-01-17 10:37
A related issue: following qoto.org is also impossible right now. I migrated from another server to here hoping to get less bugs but it seems it's just Mastodon in general.

**Comment by freiheit** [comment] 2023-01-17 20:50
Same underlying issue as #264 ?

**Comment by jimrhiz** [comment] 2023-01-18 02:35
Has kolektiva.social ever been silenced or suspended on hachyderm.io? It isn't now, as far as I can tell. However, I am not able to follow a particular hachyderm account from kolektiva. I can see the profile (so I'm not blocked at present), and a follow appears to work at first, but when I look at the profile a bit later on, I am actually still not following.

Oddly, it only seems to be one account. I have successfully followed a different hachyderm user from kolektiva.

**Comment by quintessence** [comment] 2023-02-13 05:26
👋 Apologies @jimrhiz - missed this. No: kolektiva.social has never been moderated at the server level on Hachyderm (so no limit / silence or suspend).

**Comment by jimrhiz** [comment] 2023-02-13 07:16
Thank you for the reply, @quintessence. I still can't follow that account, with the same misbehaviour as before, so this remains a mystery.

**Comment by lypanov** [comment] 2023-03-04 10:36
I can't believe this is still broken. Given I can't follow people I previously was able to I'll just move to a different and far more liberal server as that is apparently the only way I'll be able to view everything I want to. It's just a tech blogger FFS!

**Comment by dmah42** [comment] 2023-03-04 10:46
we have been waiting for the upstream to offer a fix for this issue.  unfortunately, there's not much we can do within the limitations put on us by the code.

in the latest release this is fixed _going forward_ apparently, but it's not clear it will fix any relationships between community servers currently in this state.

it is as frustrating for us as it is for you.

of course, the miracle of the fediverse is that you're free to go to any community server you want, and judge that community any way you feel.

**Comment by lypanov** [comment] 2023-03-04 10:49
Yeah I've migrated to mastodon.online instead. I was hoping this would become something decentralized, but this is the second server move I've done due to issues and second content loss that has occured. Mastodon isn't ready for mainstream.

**Comment by Preskton** [comment] 2023-03-07 02:29
Thanks for the update, @lypanov. I'm going to close the issue here and note as a possible fix it in our version upgrade tracking issue.

**Closed by Preskton** 2023-03-07 02:29 UTC
Labels: Reporting Service Issue, Questions around Federation, Infra Team

**Comment by ambihelical** [comment] 2023-03-10 05:18
Interesting @Preskton. How do I follow the resolution of this bug now?
