### ISSUE TITLE
Issues with searching for users based on username

### ISSUE THREAD

**Issue by dclements** [hachyderm/community#221] opened 2022-12-18 19:44 UTC
### Please describe the issue you are seeing.

When I searched for users or domains in the search box it would historically show me a list of people.  This has been severely reduced in the last 24-48 hours or so: I insert the search term and it either times out or it only gives me one result (usually the <server>@<server>), whereas previously it would give me a list of results and would consistently include those I follow. 

Sometimes if I wait a minute or two and try again from the web app I can get a success (though to be clear it still happens there), but not from within metatext. 

Reproduction cases:

* Search under "people" for "eldritch.cafe" 
* If I search for "hachyderm.io" it shows me a bunch of accounts that have the same preferredName but not the same actual underlying user and none of them are _on_ hachyderm.io. As of at least a few days ago this was not the case and it would have given me an assortment from hachyderm.io and not paid close attention to the preferredName.
* Something similar if I search for "infosec.exchange": I get a few people who have it in their username and the support address, but not any other results.

1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.

Not that shows up in metatext. I haven't gotten that case to fully reproduce in the web browser (where it tends to just show me chaotic or a singular result).

2. When are you seeing the issue? When you are submitting posts? Uploading media?

When I search for users on other instances (usually to see if I want to follow them after seeing their name on twitter).

4. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

I am using Safari on an iPad and Metatext on the same system on a reasonable internet connection. I have not tested in other environments outside of those two. 

### How long have you noticed this issue?

Two or three days

### What geographic region are you accessing Hachyderm from?

US Mountain West

**Comment by quintessence** [comment] 2022-12-20 18:42
👋 Hello, mod here

I tried to reproduce and this is what I'm seeing:

<img width="907" alt="Screen Shot 2022-12-20 at 10 37 37" src="https://user-images.githubusercontent.com/3387286/208741816-29527608-03d4-4dcc-ba75-aad64b8ac12d.png">
<img width="1056" alt="Screen Shot 2022-12-20 at 10 39 55" src="https://user-images.githubusercontent.com/3387286/208741817-0080830b-595e-41ab-885b-821b2fe7f79a.png">

When you search you should see either local users that match your criteria or posts / users that you've interacted with via following, boosting, or liking their content. Is this what you are seeing?

For the Hachyderm search in particular, looks like there are a lot of Twitter bridges inundating the results, so you might need to "load more" a few times to find who you're looking for.

**Comment by quintessence** [comment] 2022-12-27 21:14
I'm going to go ahead and close this issue for now - please let us know if it continues / you have any further questions :)

**Closed by quintessence** 2022-12-27 21:14 UTC
Labels: Reporting Service Issue, Questions around Federation
